# action.yml
name: 'PROD-Build_PWPusher'
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    container: circleci/ruby:2.7.2-node
    steps:
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: gem system updates
        run: |
          gem update --system
          gem update bundler
          gem --version

      - name: Install dependencies
        run: bundle install --path vendor/bundle

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: ~/repo

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          path: ~/repo
          context: ./
          file: '/pwpush-ephemeral/Dockerfile'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pwpush-ephemeral:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}