# action.yml
name: 'PROD-Build_PWPusher'

on: [push]

description: 'Build PWPusher docker for production enviroment'
runs:
  using: 'docker'
  image: '\PasswordPusher\containerization\pwpush-ephemeral\'